version: '3.7'

services:
  web:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - "8200"
    ports:
      - 8010:8888
    volumes:
      - ./:/code/
    env_file: .env
    working_dir: /code/
    command: /root/.cache/pypoetry/virtualenvs/formy-MATOk_fk-py3.9/bin/jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root
